"""Deterministic V13.27.1.15 candidate inventory frozen before results."""

from __future__ import annotations

from typing import Any, Mapping

from alphapilot.evolution.registry.hashing import stable_hash
from alphapilot.exit_policy.canonical import canonical_exit_policy, exit_policy_hash
from alphapilot.exit_policy.models import ExitPolicy, ExitPolicyMode


def _policy(
    mode: ExitPolicyMode,
    maximum_hold_bars: int,
    parameters: Mapping[str, Any],
) -> ExitPolicy:
    return ExitPolicy(
        mode=mode,
        maximumHoldBars=maximum_hold_bars,
        parameters=dict(parameters),
        initialStopMayWiden=False,
    )


def _candidate(
    *,
    variant_id: str,
    candidate_id: str,
    family_id: str,
    timeframe: str,
    direction: str,
    strategy_type: str,
    hypothesis: str,
    falsification: str,
    feature_definition: Mapping[str, Any],
    entry_definition: Mapping[str, Any],
    stop_definition: Mapping[str, Any],
    policy: ExitPolicy,
    exit_rationale: str,
    simple_benchmark: str,
    complexity_score: int,
    origin_lineage: str,
    diagnostic_only: bool = False,
) -> dict[str, Any]:
    canonical_policy = canonical_exit_policy(policy)
    policy_hash = exit_policy_hash(policy)
    semantic_core = {
        "familyId": family_id,
        "timeframe": timeframe,
        "direction": direction,
        "strategyType": strategy_type,
        "featureDefinition": dict(feature_definition),
        "entryDefinition": dict(entry_definition),
    }
    definition_core = {
        **semantic_core,
        "variantId": variant_id,
        "initialStopDefinition": dict(stop_definition),
        "exitPolicyHash": policy_hash,
        "maximumHold": policy.maximumHoldBars,
        "diagnosticOnly": diagnostic_only,
    }
    return {
        "candidateId": candidate_id,
        "familyId": family_id,
        "variantId": variant_id,
        "timeframe": timeframe,
        "direction": direction,
        "strategyType": strategy_type,
        "humanHypothesisZh": hypothesis,
        "falsificationCriteriaZh": falsification,
        "featureDefinition": dict(feature_definition),
        "entryDefinition": dict(entry_definition),
        "initialStopDefinition": {**dict(stop_definition), "mayWiden": False},
        "exitPolicy": canonical_policy,
        "exitPolicyRationaleZh": exit_rationale,
        "maximumHold": policy.maximumHoldBars,
        "simpleBenchmark": simple_benchmark,
        "complexityScore": complexity_score,
        "semanticFingerprint": stable_hash(semantic_core, prefix="advisory_r_semantic"),
        "strategyDefinitionHash": stable_hash(definition_core, prefix="advisory_r_strategy"),
        "exitPolicyHash": policy_hash,
        "originLineage": origin_lineage,
        "diagnosticOnly": diagnostic_only,
    }


def build_candidate_inventory() -> list[dict[str, Any]]:
    """Return the ten preregistered candidates without performance fields."""

    candidates = [
        _candidate(
            variant_id="S01",
            candidate_id="s01_bear_idiosyncratic_selloff_recovery_4h",
            family_id="idiosyncratic_selloff_recovery",
            timeframe="4h",
            direction="long",
            strategy_type="event",
            hypothesis="熊市中相对 BTC 与核心池出现极端负残差后，价格收回可形成短期恢复。",
            falsification="成本后平均净 R 或总净 R 不为正，或正月份不足一半。",
            feature_definition={
                "marketRegime": "btc_close_below_ema_200",
                "residualWindow": 30,
                "residualZMaximum": -2.25,
                "recoveryBars": 2,
            },
            entry_definition={"kind": "residual_reclaim", "minimumRecoveryZ": 0.35},
            stop_definition={"kind": "atr", "multiple": 1.6},
            policy=_policy(
                ExitPolicyMode.HYBRID,
                24,
                {
                    "partialAtR": 0.7,
                    "partialFraction": 0.4,
                    "remainderMode": "structure",
                    "structureRule": {
                        "kind": "residual_neutral_zone",
                        "absoluteZscoreMaximum": 0.35,
                    },
                },
            ),
            exit_rationale="残差恢复是主机制；先减仓，再在关系修复或时限到达时退出。",
            simple_benchmark="same_event_fixed_12_bar_exit",
            complexity_score=4,
            origin_lineage="v13.27.1.13_bear_regime_posthoc_clue_new_trial",
        ),
        _candidate(
            variant_id="S02",
            candidate_id="s02_btc_lead_lag_continuation_1h",
            family_id="btc_lead_lag",
            timeframe="1h",
            direction="conditional",
            strategy_type="event",
            hypothesis="BTC 单小时显著方向冲击后，尚未同步的高 beta 币种存在延迟同向反应。",
            falsification="延迟反应在成本后无正净 R，或收益只集中于单月。",
            feature_definition={"btcImpulseZ": 2.0, "lagWindow": 3, "betaWindow": 168},
            entry_definition={"kind": "btc_lead_continuation", "maximumFollowerMoveFraction": 0.45},
            stop_definition={"kind": "atr", "multiple": 1.4},
            policy=_policy(
                ExitPolicyMode.PARTIAL_THEN_TRAILING,
                24,
                {"partialAtR": 0.8, "partialFraction": 0.35, "trailingAtrMultiple": 1.8},
            ),
            exit_rationale="延续效应可能扩展，部分兑现后用 ATR 收紧剩余风险。",
            simple_benchmark="btc_impulse_next_6_bar_direction",
            complexity_score=4,
            origin_lineage="new_btc_lead_lag_trial",
        ),
        _candidate(
            variant_id="S03",
            candidate_id="s03_btc_lead_lag_overreaction_reversion_1h",
            family_id="btc_lead_lag",
            timeframe="1h",
            direction="conditional",
            strategy_type="event",
            hypothesis="BTC 冲击后跟随币过度反应时，超额变动会向短期关系均值回归。",
            falsification="过度反应后的反向交易成本后无正净 R。",
            feature_definition={"btcImpulseZ": 2.0, "lagWindow": 3, "overreactionRatio": 1.55},
            entry_definition={"kind": "btc_lead_overreaction_reversion", "confirmationBars": 2},
            stop_definition={"kind": "atr", "multiple": 1.35},
            policy=_policy(
                ExitPolicyMode.STRUCTURE_OR_TIME,
                18,
                {"structureRule": {"kind": "event_reversal", "confirmationBars": 2}},
            ),
            exit_rationale="当冲击反转被确认或持有时限到达时退出，不设置事后固定目标。",
            simple_benchmark="btc_impulse_contemporaneous_reversal",
            complexity_score=4,
            origin_lineage="new_btc_lead_lag_trial",
        ),
        _candidate(
            variant_id="S04",
            candidate_id="s04_pair_residual_mean_reversion_1h",
            family_id="pair_residual_mean_reversion",
            timeframe="1h",
            direction="pair_relative",
            strategy_type="event",
            hypothesis="长期高相关币对的标准化价差极端偏离后会回到预注册中性区。",
            falsification="价差极端事件在成本后没有稳定回归收益。",
            feature_definition={"pairWindow": 240, "minimumCorrelation": 0.75, "entryResidualZ": 2.2},
            entry_definition={"kind": "pair_residual_extreme", "requireTurn": True},
            stop_definition={"kind": "residual_z", "maximumAdverseZ": 3.4},
            policy=_policy(
                ExitPolicyMode.STRUCTURE_OR_TIME,
                36,
                {"structureRule": {"kind": "residual_neutral_zone", "absoluteZscoreMaximum": 0.25}},
            ),
            exit_rationale="交易目标是关系恢复，因此以残差中性区而非固定 R 退出。",
            simple_benchmark="pair_residual_zero_cross",
            complexity_score=5,
            origin_lineage="new_pair_relationship_trial",
        ),
        _candidate(
            variant_id="S05",
            candidate_id="s05_correlation_break_recovery_4h",
            family_id="correlation_break",
            timeframe="4h",
            direction="relative_recovery",
            strategy_type="event",
            hypothesis="稳定关系突然破裂但共同趋势未变时，相关性和残差可能恢复。",
            falsification="关系破裂后继续恶化，成本后恢复交易无正净 R。",
            feature_definition={"correlationWindow": 60, "baselineMinimum": 0.75, "breakMaximum": 0.25},
            entry_definition={"kind": "correlation_break_recovery", "residualTurnBars": 2},
            stop_definition={"kind": "atr", "multiple": 1.7},
            policy=_policy(
                ExitPolicyMode.HYBRID,
                24,
                {
                    "partialAtR": 0.6,
                    "partialFraction": 0.35,
                    "remainderMode": "structure",
                    "structureRule": {"kind": "correlation_recovery", "minimumCorrelation": 0.6},
                },
            ),
            exit_rationale="先降低风险，再在相关性恢复或时间到期时退出。",
            simple_benchmark="correlation_break_equal_hold",
            complexity_score=5,
            origin_lineage="new_pair_relationship_trial",
        ),
        _candidate(
            variant_id="S06",
            candidate_id="s06_correlation_break_decoupling_4h",
            family_id="correlation_break",
            timeframe="4h",
            direction="break_direction",
            strategy_type="event",
            hypothesis="关系破裂伴随相对强度扩张时，脱钩可能延续而非立即回归。",
            falsification="脱钩方向在成本后不能延续，或回撤超过预筛上限。",
            feature_definition={"correlationWindow": 60, "breakMaximum": 0.2, "relativeStrengthBars": 6},
            entry_definition={"kind": "correlation_break_continuation", "minimumRelativeMoveZ": 1.5},
            stop_definition={"kind": "atr", "multiple": 1.6},
            policy=_policy(
                ExitPolicyMode.PARTIAL_THEN_TRAILING,
                30,
                {"partialAtR": 0.9, "partialFraction": 0.3, "trailingAtrMultiple": 2.0},
            ),
            exit_rationale="脱钩延续没有固定结构终点，部分兑现后跟踪趋势。",
            simple_benchmark="correlation_break_next_6_bar_direction",
            complexity_score=5,
            origin_lineage="new_pair_relationship_trial",
        ),
        _candidate(
            variant_id="S07",
            candidate_id="s07_volatility_shock_asymmetry_4h",
            family_id="volatility_shock_asymmetry",
            timeframe="4h",
            direction="conditional",
            strategy_type="event",
            hypothesis="极端波动冲击后的延续与反转概率具有方向不对称性。",
            falsification="分方向事件在成本后没有正的组合净 R。",
            feature_definition={"atrPercentileWindow": 180, "shockPercentile": 0.95, "closeLocationThreshold": 0.75},
            entry_definition={"kind": "directional_volatility_shock", "confirmationBars": 1},
            stop_definition={"kind": "atr", "multiple": 1.8},
            policy=_policy(
                ExitPolicyMode.PARTIAL_THEN_TRAILING,
                18,
                {"partialAtR": 0.75, "partialFraction": 0.4, "trailingAtrMultiple": 1.6},
            ),
            exit_rationale="冲击后的单边扩张用部分止盈和因果 ATR 跟踪管理。",
            simple_benchmark="volatility_shock_fixed_6_bar",
            complexity_score=3,
            origin_lineage="new_volatility_asymmetry_trial",
        ),
        _candidate(
            variant_id="S08",
            candidate_id="s08_utc_session_transition_1h",
            family_id="utc_session_transition",
            timeframe="1h",
            direction="conditional",
            strategy_type="event",
            hypothesis="UTC 交易时段转换附近的流动性与方向延续具有可重复但短暂的边际。",
            falsification="扣除成本后时段效应消失或正月份不足一半。",
            feature_definition={"utcEntryHours": [7, 15, 20], "trendWindow": 6, "minimumVolumeRatio": 1.1},
            entry_definition={"kind": "utc_session_transition", "directionFromPriorBars": 3},
            stop_definition={"kind": "atr", "multiple": 1.2},
            policy=_policy(ExitPolicyMode.FIXED_R, 12, {"targetR": 1.2}),
            exit_rationale="短时段效应的目标小于 2R，并由最大持有期限制暴露。",
            simple_benchmark="same_hour_unconditional_direction",
            complexity_score=2,
            origin_lineage="new_session_microstructure_trial",
        ),
        _candidate(
            variant_id="S09",
            candidate_id="s09_beta_defensive_rotation_4h",
            family_id="beta_defensive_rotation",
            timeframe="4h",
            direction="cross_sectional_long_short",
            strategy_type="portfolio",
            hypothesis="BTC 风险转弱时，低 beta 币相对高 beta 币具有防御性超额收益。",
            falsification="成本后多空组合收益不为正或回撤超过 35%。",
            feature_definition={"betaWindow": 90, "btcTrendWindow": 50, "rebalanceBars": 6},
            entry_definition={"kind": "beta_defensive_rotation", "longQuantile": 0.3, "shortQuantile": 0.3},
            stop_definition={"kind": "portfolio_drawdown", "riskBudgetR": 1.0},
            policy=_policy(
                ExitPolicyMode.STRUCTURE_OR_TIME,
                30,
                {"structureRule": {"kind": "beta_rank_exit", "maximumRankPercentile": 0.5}},
            ),
            exit_rationale="组合在 beta 排名失效或再平衡时限到达时退出。",
            simple_benchmark="equal_weight_representative_universe",
            complexity_score=4,
            origin_lineage="new_cross_sectional_rotation_trial",
        ),
        _candidate(
            variant_id="S10",
            candidate_id="s10_orthogonal_weak_signal_matrix_4h",
            family_id="orthogonal_weak_signal_matrix",
            timeframe="4h",
            direction="conditional",
            strategy_type="event",
            hypothesis="三个低相关弱信号在方向一致时可能形成可诊断的增量。",
            falsification="组合后仍不能超过零交易基准，或贡献高度集中。",
            feature_definition={"signals": ["residual_turn", "volume_surprise", "trend_slope"], "minimumVotes": 2},
            entry_definition={"kind": "orthogonal_vote", "confirmationBars": 1},
            stop_definition={"kind": "atr", "multiple": 1.5},
            policy=_policy(
                ExitPolicyMode.STRUCTURE_OR_TIME,
                24,
                {"structureRule": {"kind": "trend_invalidation", "fastWindow": 12, "slowWindow": 48}},
            ),
            exit_rationale="诊断候选在趋势结构失效或时限到达时退出。",
            simple_benchmark="equal_weight_component_signals",
            complexity_score=6,
            origin_lineage="new_orthogonal_diagnostic_trial",
            diagnostic_only=True,
        ),
    ]
    return sorted(candidates, key=lambda row: str(row["variantId"]))

